##########################################################################
##########          Wise Information Technology of med          ##########
##########          Witmed System Consumer Configuration        ##########
##########          @author Arthur                              ##########
##########          @version 1.0.0                              ##########
##########          @date 2022/2/15                             ##########
##########          @since 1.0.0                                ##########
##########################################################################
###### 配置项目启动端口号
server:
  port: 11111
spring:
  ###### 配置项目应用名
  application:
    name: witmed-system-consumer
  ###### 配置项目需要加载的环境
  profiles:
    active: commons