##########################################################################
##########          Wise Information Technology of med          ##########
##########          Commons Configuration Information           ##########
##########          @author Arthur                              ##########
##########          @version 1.0.0                              ##########
##########          @date 2022/2/14                             ##########
##########          @since 1.0.0                                ##########
##########################################################################
###### 配置开启 Spring Boot 对于 Bean id 的 Override 机制
spring:
  main:
    allow-bean-definition-overriding: true
###### 配置 Eureka Client 链接 Eureka Server 的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/