############################################################################
##########          Witmed Project Commons Configuration          ##########
##########          @author: Arthur                               ##########
##########          @date 2022/1/18                               ##########
##########          @version 1.0.0                                ##########
##########          @since 1.0.0                                  ##########
############################################################################
###### 配置开启 Spring Boot 对于 Bean id 的 Override 机制
spring:
  main:
    allow-bean-definition-overriding: true
###### 配置 Eureka Client 链接 Eureka Server 的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/