##########################################################################
##########          Wise Information Technology of med          ##########
##########          Registry Application Information            ##########
##########          @author Arthur                              ##########
##########          @version 1.0.0                              ##########
##########          @date 2022/2/14                             ##########
##########          @since 1.0.0                                ##########
##########################################################################
########## 配置项目启动端口号
server:
  port: 9999
spring:
  ########## 配置项目应用名
  application:
    name: witmed-registry
  ########## 开启 Spring Boot 对于 Bean id 的 Override 机制
  main:
    allow-bean-definition-overriding: true
########## 配置 Eureka 信息
eureka:
  ########## 配置项目主机名
  instance:
    hostname: localhost
  ########## 配置客户端连接信息
  client:
    ########## 禁止注册中心项目将自己的服务进行注册
    register-with-eureka: false
    ########## 禁止注册中心去其他注册中心中发现服务
    fetch-registry: false
    ########## 配置注册中心连接地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka