##############################################################
##########          Witmed System Provider          ##########
##########          @author: Arthur                 ##########
##########          @date 2022/1/18                 ##########
##########          @version 1.0.0                  ##########
##########          @since 1.0.0                    ##########
##############################################################
###### 配置项目启动端口号
server:
  port: 11199
spring:
  ###### 配置项目应用名
  application:
    name: witmed-system-provider
  ###### 配置项目需要加载的环境
  profiles:
    active: data, commons