##########################################################################
##########          Wise Information Technology of med          ##########
##########          Witmed Patient Consumer Configuration       ##########
##########          @author Arthur                              ##########
##########          @version 1.0.0                              ##########
##########          @date 2022/2/19                             ##########
##########          @since 1.0.0                                ##########
##########################################################################
###### 配置项目启动端口号
server:
  port: 31111
spring:
  ###### 配置项目应用名
  application:
    name: witmed-patient-consumer
  ###### 配置项目需要加载的环境
  profiles:
    active: commons